//! Parity tests for the data and optimizer-hook layer — steps 48–51 — against
//! golden fixtures generated by the Python DeZero reference
//! (`vendor/dezero-python`).
//!
//! Three things are pinned here, and they fail in three different ways:
//!
//! * **`spiral_training`** — a 300-iteration `MLP((10, 3))` classification run
//!   on the spiral, softmax cross-entropy, plain SGD at `lr = 1.0`. Compared at
//!   every one of the 300 steps and on all four final weight arrays. It is the
//!   integration test for steps 41–48 taken together, and a divergence in any
//!   single piece shows up within a handful of iterations.
//! * **`dataloader_batches`** — the exact batch boundaries of
//!   `DataLoader(train, batch_size=32, shuffle=False)` over 300 examples: nine
//!   full batches and a final one of twelve, every row in Python's order.
//! * **`hook_weight_decay`** / **`hook_clip_grad_*`** — one application of each
//!   hook to a known gradient, including the case where clipping does not fire.
//!
//! The spiral run agrees with Python to within `4.5e-16` relative on the loss
//! trace and `6.2e-15` on the worst final weight — floating-point noise, not
//! agreement to a tolerance. The assertions below use the suite's usual
//! `1e-4` bound anyway, because a tolerance chosen to sit just above today's
//! rounding is a tolerance that fails on the next compiler.
//!
//! The spiral data itself travels with the fixture. `get_spiral` draws from
//! `np.random.randn` and shuffles with `np.random.permutation`, neither of
//! which any generator in this crate reproduces (`docs/ARCHITECTURE.md`), so
//! "seed both sides" was never an option.
//!
//! Regenerate with `python tests/parity/gen_fixtures.py`.

use dezero::{
    Batch, ClipGrad, DataLoader, Dataset, FreezeParam, Hook, Layer, Mlp, Optimizer, Parameter, Sgd,
    Spiral, Variable, WeightDecay, softmax_cross_entropy,
};
use ndarray::{ArrayD, IxDyn};
use serde::Deserialize;

/// numpy `allclose` defaults, for forward values.
const RTOL: f64 = 1e-5;
const ATOL: f64 = 1e-8;
/// Gradients, and anything downstream of three hundred of them, accumulate
/// through more floating-point operations than a forward pass; still far
/// tighter than any real bug would survive.
const GRAD_RTOL: f64 = 1e-4;

/// An ndarray serialised rank-generically: `shape: []` is a 0-d scalar.
#[derive(Debug, Deserialize)]
struct Arr {
    shape: Vec<usize>,
    data: Vec<f64>,
}

impl Arr {
    fn to_array(&self) -> ArrayD<f64> {
        ArrayD::from_shape_vec(IxDyn(&self.shape), self.data.clone())
            .expect("fixture shape and data length should agree")
    }
}

/// Step 48: the exact 300-point spiral Python's `Spiral(train=True)` builds.
#[derive(Debug, Deserialize)]
struct SpiralData {
    x: Arr,
    t: Vec<usize>,
}

/// Step 48: a full classification run with every initial weight pinned.
///
/// Python's `MLP` names its layers `l0` and `l1`, so `W1`/`b1` here are the
/// *first* layer's — the fixture generator reads `model.l0.W`.
#[derive(Debug, Deserialize)]
struct SpiralTraining {
    #[serde(rename = "W1")]
    w1: Arr,
    b1: Arr,
    #[serde(rename = "W2")]
    w2: Arr,
    b2: Arr,
    lr: f64,
    iterations: usize,
    losses: Vec<f64>,
    #[serde(rename = "final_W1")]
    final_w1: Arr,
    final_b1: Arr,
    #[serde(rename = "final_W2")]
    final_w2: Arr,
    final_b2: Arr,
}

/// Step 50: every batch of one unshuffled epoch.
#[derive(Debug, Deserialize)]
struct DataLoaderBatches {
    batch_size: usize,
    data_size: usize,
    batches: Vec<FixtureBatch>,
}

#[derive(Debug, Deserialize)]
struct FixtureBatch {
    x: Arr,
    t: Vec<usize>,
}

/// Step 50: `WeightDecay(rate)` over two parameters.
#[derive(Debug, Deserialize)]
struct WeightDecayFixture {
    rate: f64,
    p1: Arr,
    p2: Arr,
    g1_in: Arr,
    g2_in: Arr,
    g1_out: Arr,
    g2_out: Arr,
}

/// Step 50: `ClipGrad(max_norm)` over two parameters.
#[derive(Debug, Deserialize)]
struct ClipGradFixture {
    max_norm: f64,
    g1_in: Arr,
    g2_in: Arr,
    g1_out: Arr,
    g2_out: Arr,
}

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = format!(
        "{}/../../tests/parity/fixtures/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {path}: {e}"));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("fixture {name} should match the expected schema: {e}"))
}

fn assert_close(what: &str, actual: &ArrayD<f64>, expected: &ArrayD<f64>, rtol: f64) {
    assert_eq!(
        actual.shape(),
        expected.shape(),
        "{what}: shape mismatch (Rust {:?} vs Python {:?})",
        actual.shape(),
        expected.shape()
    );
    for (a, e) in actual.iter().zip(expected.iter()) {
        assert!(
            (a - e).abs() <= ATOL + rtol * e.abs(),
            "{what}: diverged from the Python reference\n  Rust:   {actual:?}\n  Python: {expected:?}"
        );
    }
}

fn data_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.data()
        .unwrap_or_else(|| panic!("{what} should hold data"))
}

fn grad_of(param: &Parameter, what: &str) -> ArrayD<f64> {
    param
        .grad()
        .and_then(|g| g.data())
        .unwrap_or_else(|| panic!("{what} should have a gradient"))
}

/// The reference's `Spiral(train=True)`, rebuilt from the fixture arrays.
fn spiral() -> Spiral {
    let fx: SpiralData = load("spiral_data");
    Spiral::new(fx.x.to_array(), fx.t)
}

// --- step 48: the dataset --------------------------------------------------

/// The fixture is the dataset, so this checks the *plumbing*: that
/// [`Spiral::new`] hands back what it was given, row by row, with the labels
/// still attached to the right rows.
#[test]
fn the_spiral_dataset_matches_python() {
    let fx: SpiralData = load("spiral_data");
    let expected = fx.x.to_array();
    let train = Spiral::new(expected.clone(), fx.t.clone());

    assert_eq!(train.len(), 300, "100 points on each of three arms");
    assert_eq!(expected.shape(), &[300, 2]);
    assert_close("spiral inputs", train.inputs(), &expected, RTOL);
    assert_eq!(train.labels(), fx.t.as_slice());

    // Every example, one at a time, is the matching row of the array.
    for index in 0..train.len() {
        let row = train.input(index);
        assert_eq!(row.shape(), &[2], "example {index}");
        assert!(
            (row[[0]] - expected[[index, 0]]).abs() < f64::EPSILON
                && (row[[1]] - expected[[index, 1]]).abs() < f64::EPSILON,
            "example {index} is not row {index}"
        );
        assert_eq!(train.label(index), Some(fx.t[index]));
    }

    // Three classes, a hundred each, and shuffled -- Python shuffles inside
    // `get_spiral`, so an unshuffled loader still sees them interleaved.
    let mut counts = [0_usize; 3];
    for &label in train.labels() {
        counts[label] += 1;
    }
    assert_eq!(counts, [100, 100, 100]);
    assert!(
        train.labels()[..100]
            .iter()
            .any(|&t| t != train.labels()[0]),
        "the fixture's labels are shuffled"
    );
}

// --- step 48: the training run --------------------------------------------

/// Replays Python's 300-iteration spiral classification run step for step.
///
/// `MLP((10, 3))` with the default `sigmoid` activation, `softmax_cross_entropy`
/// against the integer labels, plain SGD at `lr = 1.0`, full batch. Compared
/// against Python's loss at every iteration and all four weights at the end.
///
/// This is the integration test steps 41-48 build up to: `Linear`'s lazy
/// shaping, `Layer` registration, `sigmoid`, the gather in the cross-entropy
/// forward and the scatter in its backward, `cleargrads`, and `SGD` all have to
/// be right at once, and each iteration starts from the previous one's weights,
/// so an error anywhere compounds rather than averaging out.
#[test]
fn spiral_training_run_matches_python() {
    let data: SpiralData = load("spiral_data");
    let fx: SpiralTraining = load("spiral_training");

    assert_eq!(
        fx.losses.len(),
        fx.iterations,
        "the fixture should record one loss per iteration"
    );

    let x = Variable::new(data.x.to_array());
    let labels = data.t;

    // Python's `MLP((10, 3))`: two lazily-shaped Linear layers with a sigmoid
    // between them and nothing after the last.
    let model = Mlp::new(&[10, 3]);

    // The generator forces the weights into existence with one forward pass and
    // then overwrites all four; do the same, or the shapes are not yet known.
    model.forward(&x);
    let first = &model.layers()[0];
    let second = &model.layers()[1];
    first.weight().set_data(fx.w1.to_array());
    first
        .bias()
        .expect("Linear has a bias")
        .set_data(fx.b1.to_array());
    second.weight().set_data(fx.w2.to_array());
    second
        .bias()
        .expect("Linear has a bias")
        .set_data(fx.b2.to_array());

    let mut optimizer = Sgd::new(fx.lr);
    optimizer.setup(&model);

    let mut losses = Vec::with_capacity(fx.iterations);
    for _ in 0..fx.iterations {
        let prediction = model.forward(&x);
        let loss = softmax_cross_entropy(&prediction, &labels);
        model.cleargrads();
        loss.backward();
        optimizer.update();
        losses.push(data_of(&loss, "loss").sum());
    }

    // Compared iteration by iteration rather than only at the end: a divergence
    // shows up at the step it started on, not three hundred steps later.
    let shape = IxDyn(&[losses.len()]);
    let actual = ArrayD::from_shape_vec(shape.clone(), losses).expect("shape matches length");
    let expected = ArrayD::from_shape_vec(shape, fx.losses).expect("shape matches length");
    assert_close("spiral loss trace", &actual, &expected, GRAD_RTOL);

    // And the run really did learn something: 1.11 -> 0.72.
    assert!(
        actual[[0]] > actual[[fx.iterations - 1]],
        "the loss must fall over the run"
    );

    // The trace could in principle match while the weights drifted, so the
    // final parameters are pinned too.
    for (what, parameter, expected) in [
        ("W1", first.weight(), &fx.final_w1),
        ("b1", first.bias().expect("bias"), &fx.final_b1),
        ("W2", second.weight(), &fx.final_w2),
        ("b2", second.bias().expect("bias"), &fx.final_b2),
    ] {
        assert_close(
            &format!("final {what}"),
            &data_of(parameter, what),
            &expected.to_array(),
            GRAD_RTOL,
        );
    }
}

// --- step 50: the DataLoader ----------------------------------------------

/// Every batch boundary of one unshuffled epoch, against Python's.
///
/// 300 examples at a batch size of 32 is `ceil(300 / 32) = 10` batches: nine of
/// 32 and a last one of **12**. Dropping the short batch — which `floor` would
/// do, and which several frameworks default to — loses twelve examples an epoch
/// and is invisible in a loss curve.
#[test]
fn dataloader_batches_match_python() {
    let fx: DataLoaderBatches = load("dataloader_batches");
    let train = spiral();

    assert_eq!(fx.data_size, train.len());
    assert_eq!(fx.batches.len(), 10, "ceil(300 / 32)");

    let mut loader = DataLoader::new(&train, fx.batch_size, false);
    assert_eq!(loader.max_iter(), fx.batches.len());
    assert_eq!(loader.data_size(), fx.data_size);

    let batches: Vec<Batch> = loader.by_ref().collect();
    assert_eq!(
        batches.len(),
        fx.batches.len(),
        "the loader must yield exactly one epoch"
    );

    let mut total_rows = 0;
    for (index, (actual, expected)) in batches.iter().zip(&fx.batches).enumerate() {
        let expected_x = expected.x.to_array();
        assert_eq!(
            actual.x.shape(),
            expected_x.shape(),
            "batch {index} has the wrong shape"
        );
        assert_close(&format!("batch {index} x"), &actual.x, &expected_x, RTOL);
        assert_eq!(actual.t, expected.t, "batch {index} labels");
        total_rows += actual.len();
    }

    assert_eq!(total_rows, fx.data_size, "every example, exactly once");

    // The boundary this fixture exists for.
    let sizes: Vec<usize> = batches.iter().map(Batch::len).collect();
    assert_eq!(sizes, vec![32, 32, 32, 32, 32, 32, 32, 32, 32, 12]);

    // And the epoch really is over.
    assert!(loader.next().is_none());
}

/// The same epoch again after a `reset`, since `shuffle=False` makes the order
/// deterministic — Python's `__next__` resets on its way out and produces the
/// identical sequence next time round.
#[test]
fn an_unshuffled_epoch_repeats_exactly() {
    let fx: DataLoaderBatches = load("dataloader_batches");
    let train = spiral();
    let mut loader = DataLoader::new(&train, fx.batch_size, false);

    let first: Vec<Batch> = loader.by_ref().collect();
    loader.reset();
    let second: Vec<Batch> = loader.collect();
    assert_eq!(first, second);
}

/// Shuffling changes the order and nothing else: the same 300 examples, each
/// once, with its own label still attached.
#[test]
fn a_shuffled_epoch_is_a_permutation_of_the_unshuffled_one() {
    let fx: DataLoaderBatches = load("dataloader_batches");
    let train = spiral();

    let mut ordered: Vec<(u64, usize)> = Vec::new();
    for batch in DataLoader::new(&train, fx.batch_size, false) {
        collect_rows(&batch, &mut ordered);
    }

    let mut shuffled: Vec<(u64, usize)> = Vec::new();
    let mut loader = DataLoader::new(&train, fx.batch_size, true).with_seed(4);
    for batch in loader.by_ref() {
        collect_rows(&batch, &mut shuffled);
    }

    assert_ne!(ordered, shuffled, "shuffling did something");
    let (mut a, mut b) = (ordered, shuffled);
    a.sort_unstable();
    b.sort_unstable();
    assert_eq!(a, b, "and it did nothing but reorder");

    // The short final batch survives shuffling.
    loader.reset();
    let sizes: Vec<usize> = loader.map(|batch| batch.len()).collect();
    assert_eq!(sizes, vec![32, 32, 32, 32, 32, 32, 32, 32, 32, 12]);
}

/// A row's two coordinates, as bits, paired with its label — a hashable
/// identity for "this example", so that two epochs can be compared as sets.
fn collect_rows(batch: &Batch, into: &mut Vec<(u64, usize)>) {
    for (row, &label) in batch.x.rows().into_iter().zip(&batch.t) {
        into.push((row[0].to_bits() ^ row[1].to_bits().rotate_left(17), label));
    }
}

/// The loader feeds the network: one epoch of mini-batch training on the real
/// fixture data, end to end. Not a parity check — the mini-batch run has no
/// Python counterpart — but it is what steps 49-50 exist to make possible, and
/// it would break loudly if `Batch::input` or the label ordering were wrong.
#[test]
fn a_mini_batch_epoch_trains_the_spiral_model() {
    let train = spiral();
    let model = Mlp::new(&[10, 3]);
    let mut optimizer = Sgd::new(1.0);
    optimizer.setup(&model);

    let loss_over = |model: &Mlp| {
        let x = Variable::new(train.inputs().clone());
        data_of(
            &softmax_cross_entropy(&model.forward(&x), train.labels()),
            "loss",
        )
        .sum()
    };

    let mut loader = DataLoader::new(&train, 30, true).with_seed(11);
    let before = {
        model.forward(&Variable::new(train.inputs().clone())); // shape the weights
        loss_over(&model)
    };

    for _ in 0..20 {
        for batch in loader.by_ref() {
            let loss = softmax_cross_entropy(&model.forward(&batch.input()), &batch.t);
            model.cleargrads();
            loss.backward();
            optimizer.update();
        }
        loader.reset();
    }

    let after = loss_over(&model);
    assert!(
        after < before,
        "twenty epochs of mini-batch SGD must lower the loss: {before} -> {after}"
    );
    assert!(after < 0.9, "and lower it substantially: {after}");
}

// --- step 50: the hooks ----------------------------------------------------

/// Two parameters with known data and gradients, as the fixture built them.
fn hook_parameters(p1: &Arr, p2: &Arr, g1: &Arr, g2: &Arr) -> (Parameter, Parameter) {
    let first = Parameter::new(p1.to_array());
    let second = Parameter::new(p2.to_array());
    first.set_grad(Some(Variable::new(g1.to_array())));
    second.set_grad(Some(Variable::new(g2.to_array())));
    (first, second)
}

/// `param.grad.data += rate * param.data`, on both parameters.
///
/// The second parameter's data is negative, so a hook that took `|w|` or
/// dropped the sign would still move the first gradient the right way and the
/// second the wrong way.
#[test]
fn weight_decay_matches_python() {
    let fx: WeightDecayFixture = load("hook_weight_decay");
    let (first, second) = hook_parameters(&fx.p1, &fx.p2, &fx.g1_in, &fx.g2_in);

    WeightDecay::new(fx.rate).call(&[first.clone(), second.clone()]);

    assert_close(
        "weight decay g1",
        &grad_of(&first, "p1"),
        &fx.g1_out.to_array(),
        RTOL,
    );
    assert_close(
        "weight decay g2",
        &grad_of(&second, "p2"),
        &fx.g2_out.to_array(),
        RTOL,
    );

    // The weights themselves are untouched -- the penalty goes into the
    // gradient, not into the parameter.
    assert_close(
        "weight decay leaves p1 alone",
        &data_of(&first, "p1"),
        &fx.p1.to_array(),
        RTOL,
    );
}

/// `ClipGrad` with a cap the joint norm exceeds: every gradient is scaled by
/// the same `max_norm / (total_norm + 1e-6)`.
#[test]
fn clip_grad_matches_python_when_it_fires() {
    let fx: ClipGradFixture = load("hook_clip_grad_clips");
    let (first, second) = hook_parameters(&fx.g1_in, &fx.g2_in, &fx.g1_in, &fx.g2_in);

    // sqrt(0.01 + 0.04 + 0.09 + 0.16 + 1 + 4) = sqrt(5.3)
    let norm = ClipGrad::total_norm(&[first.clone(), second.clone()]);
    assert!(
        (norm - 5.3_f64.sqrt()).abs() < 1e-12,
        "the joint norm is {norm}"
    );
    assert!(norm > fx.max_norm, "the cap has to bite for this fixture");

    ClipGrad::new(fx.max_norm).call(&[first.clone(), second.clone()]);

    assert_close(
        "clipped g1",
        &grad_of(&first, "p1"),
        &fx.g1_out.to_array(),
        RTOL,
    );
    assert_close(
        "clipped g2",
        &grad_of(&second, "p2"),
        &fx.g2_out.to_array(),
        RTOL,
    );
}

/// The other branch: a cap far above the joint norm leaves every gradient bit
/// for bit unchanged, because `rate >= 1` short-circuits before any write.
#[test]
fn clip_grad_matches_python_when_it_does_not_fire() {
    let fx: ClipGradFixture = load("hook_clip_grad_noop");
    let (first, second) = hook_parameters(&fx.g1_in, &fx.g2_in, &fx.g1_in, &fx.g2_in);

    assert!(ClipGrad::total_norm(&[first.clone(), second.clone()]) < fx.max_norm);
    ClipGrad::new(fx.max_norm).call(&[first.clone(), second.clone()]);

    assert_eq!(
        grad_of(&first, "p1"),
        fx.g1_out.to_array(),
        "unchanged, exactly"
    );
    assert_eq!(
        grad_of(&second, "p2"),
        fx.g2_out.to_array(),
        "unchanged, exactly"
    );
    assert_eq!(fx.g1_out.to_array(), fx.g1_in.to_array());
}

/// The hooks reach the same numbers through an [`Optimizer`], which is where
/// they actually run: registered with `add_hook` and applied inside `update`,
/// before any parameter moves.
#[test]
fn an_optimizer_applies_its_hooks_before_stepping() {
    let fx: WeightDecayFixture = load("hook_weight_decay");
    let (first, second) = hook_parameters(&fx.p1, &fx.p2, &fx.g1_in, &fx.g2_in);

    // A zero learning rate isolates the hook: the gradients change, the weights
    // cannot.
    let mut optimizer = Sgd::new(0.0);
    optimizer.set_params(vec![first.clone(), second.clone()]);
    optimizer.add_hook(WeightDecay::new(fx.rate));
    optimizer.update();

    assert_close(
        "weight decay through the optimizer",
        &grad_of(&first, "p1"),
        &fx.g1_out.to_array(),
        RTOL,
    );
    assert_close(
        "weight decay through the optimizer",
        &grad_of(&second, "p2"),
        &fx.g2_out.to_array(),
        RTOL,
    );
    assert_close(
        "the weights did not move",
        &data_of(&first, "p1"),
        &fx.p1.to_array(),
        RTOL,
    );
}

/// A frozen layer contributes gradients and is then left exactly where it was,
/// while everything else trains — the transfer-learning case `FreezeParam`
/// exists for.
#[test]
fn freezing_holds_a_layer_still_across_a_training_run() {
    let train = spiral();
    let x = Variable::new(train.inputs().clone());

    let model = Mlp::new(&[10, 3]);
    model.forward(&x); // shape the weights

    let frozen_layer = &model.layers()[0];
    let trainable_layer = &model.layers()[1];
    let before = data_of(frozen_layer.weight(), "W1");
    let trainable_before = data_of(trainable_layer.weight(), "W2");

    let mut optimizer = Sgd::new(1.0);
    optimizer.setup(&model);
    optimizer.add_hook(FreezeParam::from_layer(frozen_layer));

    for _ in 0..25 {
        let loss = softmax_cross_entropy(&model.forward(&x), train.labels());
        model.cleargrads();
        loss.backward();
        optimizer.update();
    }

    assert_eq!(
        data_of(frozen_layer.weight(), "W1"),
        before,
        "the frozen layer must not have moved by so much as a bit"
    );
    assert_ne!(
        data_of(trainable_layer.weight(), "W2"),
        trainable_before,
        "while the trainable layer did"
    );
}
