//! Parity tests for the core autodiff engine against golden fixtures
//! generated by the Python DeZero reference (`vendor/dezero-python`).
//!
//! Every fixture pins both the forward result and the gradients, so these
//! tests cover the ops *and* the backward traversal that produced them.
//! Regenerate the fixtures with `python tests/parity/gen_fixtures.py`.

use dezero::{Variable, exp};
use ndarray::{ArrayD, IxDyn};
use serde::Deserialize;

/// numpy `allclose` defaults for forward values.
const RTOL: f64 = 1e-5;
const ATOL: f64 = 1e-8;
/// Gradients travel through more floating-point operations than the forward
/// pass, so they get a looser bound (still far tighter than any real bug).
const GRAD_RTOL: f64 = 1e-4;

#[derive(Debug, Deserialize)]
struct UnaryFixture {
    input: Vec<Vec<f64>>,
    output: Vec<Vec<f64>>,
    grad: Vec<Vec<f64>>,
}

#[derive(Debug, Deserialize)]
struct BinaryFixture {
    input0: Vec<Vec<f64>>,
    input1: Vec<Vec<f64>>,
    output: Vec<Vec<f64>>,
    grad0: Vec<Vec<f64>>,
    grad1: Vec<Vec<f64>>,
}

fn load(name: &str) -> String {
    let path = format!(
        "{}/../../tests/parity/fixtures/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {path}: {e}"))
}

fn to_array(rows: &[Vec<f64>]) -> ArrayD<f64> {
    let nrows = rows.len();
    let ncols = rows.first().map_or(0, Vec::len);
    let flat: Vec<f64> = rows.iter().flatten().copied().collect();
    ArrayD::from_shape_vec(IxDyn(&[nrows, ncols]), flat)
        .expect("fixture rows should form a rectangular matrix")
}

fn assert_close(what: &str, actual: &ArrayD<f64>, expected: &ArrayD<f64>, rtol: f64) {
    assert_eq!(
        actual.shape(),
        expected.shape(),
        "{what}: shape mismatch (actual {:?} vs Python {:?})",
        actual.shape(),
        expected.shape()
    );
    for (a, e) in actual.iter().zip(expected.iter()) {
        assert!(
            (a - e).abs() <= ATOL + rtol * e.abs(),
            "{what}: diverged from the Python reference\n  actual:   {actual:?}\n  expected: {expected:?}"
        );
    }
}

fn data_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.data()
        .unwrap_or_else(|| panic!("{what} should hold data"))
}

fn grad_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.grad()
        .and_then(|g| g.data())
        .unwrap_or_else(|| panic!("{what} should have a gradient after backward"))
}

/// Run a single-input fixture: build `x`, apply `f`, backward, compare both.
fn check_unary(name: &str, f: impl Fn(&Variable) -> Variable) {
    let fx: UnaryFixture = serde_json::from_str(&load(name)).expect("fixture should be valid JSON");
    let x = Variable::new(to_array(&fx.input));
    let y = f(&x);
    y.backward();

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &to_array(&fx.output),
        RTOL,
    );
    assert_close(
        &format!("{name} grad"),
        &grad_of(&x, name),
        &to_array(&fx.grad),
        GRAD_RTOL,
    );
}

/// Run a two-input fixture, checking the gradient of *both* operands.
fn check_binary(name: &str, f: impl Fn(&Variable, &Variable) -> Variable) {
    let fx: BinaryFixture =
        serde_json::from_str(&load(name)).expect("fixture should be valid JSON");
    let a = Variable::new(to_array(&fx.input0));
    let b = Variable::new(to_array(&fx.input1));
    let y = f(&a, &b);
    y.backward();

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &to_array(&fx.output),
        RTOL,
    );
    assert_close(
        &format!("{name} grad0"),
        &grad_of(&a, name),
        &to_array(&fx.grad0),
        GRAD_RTOL,
    );
    assert_close(
        &format!("{name} grad1"),
        &grad_of(&b, name),
        &to_array(&fx.grad1),
        GRAD_RTOL,
    );
}

// --- steps 02-08: single-variable functions and composition ---------------

#[test]
fn exp_matches_python() {
    check_unary("exp", exp);
}

#[test]
fn square_backward_matches_python() {
    check_unary("square_backward", |x| x * x);
}

/// step 03's composed chain, `y = square(exp(square(x)))` -- the case that
/// first requires walking more than one link of the graph.
#[test]
fn composed_chain_matches_python() {
    check_unary("composed_sq_exp_sq", |x| {
        let t = exp(&(x * x));
        &t * &t
    });
}

// --- step 14: the same variable used twice must accumulate ---------------

/// `y = x + x` -> `dy/dx == 2`. Getting 1 here is the classic step-14 bug.
#[test]
fn repeated_variable_accumulates_grad() {
    check_unary("add_same_var", |x| x + x);
}

// --- steps 20-22: the arithmetic operator set ---------------------------

#[test]
fn add_matches_python() {
    check_binary("add", |a, b| a + b);
}

#[test]
fn mul_matches_python() {
    check_binary("mul", |a, b| a * b);
}

#[test]
fn sub_matches_python() {
    check_binary("sub", |a, b| a - b);
}

#[test]
fn div_matches_python() {
    check_binary("div", |a, b| a / b);
}

#[test]
fn neg_matches_python() {
    check_unary("neg", |x| -x);
}

#[test]
fn pow_matches_python() {
    check_unary("pow3", |x| dezero::pow(x, 3.0));
}

/// Mixes scalar operands, a reused variable, and four different ops in one
/// expression -- the closest thing here to real user code.
#[test]
fn composite_arithmetic_matches_python() {
    check_unary("composite_arith", |x| &((x * x) + x) / 2.0 - x);
}
