//! Parity test comparing the Rust `square` implementation against a
//! golden fixture generated by the Python `DeZero` reference
//! implementation (see `vendor/dezero-python`).

use dezero::{Variable, square};
use ndarray::Array2;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct SquareFixture {
    input: Vec<Vec<f64>>,
    output: Vec<Vec<f64>>,
}

/// Mirrors `numpy.allclose`'s default tolerances:
/// `|a - b| <= atol + rtol * |b|`.
fn allclose(a: &Array2<f64>, b: &Array2<f64>, rtol: f64, atol: f64) -> bool {
    if a.shape() != b.shape() {
        return false;
    }
    a.iter()
        .zip(b.iter())
        .all(|(x, y)| (x - y).abs() <= atol + rtol * y.abs())
}

fn to_array2(rows: &[Vec<f64>]) -> Array2<f64> {
    let nrows = rows.len();
    let ncols = rows.first().map_or(0, Vec::len);
    let flat: Vec<f64> = rows.iter().flatten().copied().collect();
    Array2::from_shape_vec((nrows, ncols), flat)
        .expect("fixture rows should form a rectangular matrix")
}

#[test]
fn square_matches_python_reference() {
    let fixture_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/parity/fixtures/square.json"
    );
    let contents = std::fs::read_to_string(fixture_path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {fixture_path}: {e}"));
    let fixture: SquareFixture =
        serde_json::from_str(&contents).expect("fixture should be valid JSON");

    let input = to_array2(&fixture.input);
    let expected_output = to_array2(&fixture.output);

    let x = Variable::new(input.into_dyn());
    let y = square(&x);

    let actual_output = y
        .data()
        .expect("square should produce data")
        .into_dimensionality::<ndarray::Ix2>()
        .expect("square should preserve dimensionality");

    assert!(
        allclose(&actual_output, &expected_output, 1e-5, 1e-8),
        "square output did not match Python reference:\nactual: {actual_output:?}\nexpected: {expected_output:?}"
    );
}

/// The fixture only pins the forward pass, but the same input exercises the
/// backward pass: `d(x^2)/dx = 2x`, which is where the port's autodiff engine
/// actually differs from the placeholder it replaced.
#[test]
fn square_backward_matches_two_x() {
    let fixture_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../tests/parity/fixtures/square.json"
    );
    let contents = std::fs::read_to_string(fixture_path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {fixture_path}: {e}"));
    let fixture: SquareFixture =
        serde_json::from_str(&contents).expect("fixture should be valid JSON");

    let input = to_array2(&fixture.input);
    let expected_grad = input.mapv(|v| 2.0 * v);

    let x = Variable::new(input.into_dyn());
    let y = square(&x);
    y.backward();

    let actual_grad = x
        .grad()
        .and_then(|g| g.data())
        .expect("backward should fill in the gradient")
        .into_dimensionality::<ndarray::Ix2>()
        .expect("the gradient has the shape of the input");

    assert!(
        allclose(&actual_grad, &expected_grad, 1e-5, 1e-8),
        "square gradient did not match 2x:\nactual: {actual_grad:?}\nexpected: {expected_grad:?}"
    );
}
