//! Parity tests for the core autodiff engine against golden fixtures
//! generated by the Python DeZero reference (`vendor/dezero-python`).
//!
//! Every fixture pins both the forward result and the gradients, so these
//! tests cover the ops *and* the backward traversal that produced them.
//! Regenerate with `python tests/parity/gen_fixtures.py`.

use dezero::{
    Axes, Variable, broadcast_to, cos, exp, pow, reshape, sin, sum, sum_all, sum_to, tanh,
    transpose,
};
use ndarray::{ArrayD, IxDyn};
use serde::Deserialize;

/// numpy `allclose` defaults, for forward values.
const RTOL: f64 = 1e-5;
const ATOL: f64 = 1e-8;
/// Gradients accumulate through more floating-point operations than the
/// forward pass, so they get a looser bound -- still far tighter than any
/// real bug would survive.
const GRAD_RTOL: f64 = 1e-4;

/// An ndarray serialised rank-generically: `shape: []` is a 0-d scalar.
#[derive(Debug, Deserialize)]
struct Arr {
    shape: Vec<usize>,
    data: Vec<f64>,
}

impl Arr {
    fn to_array(&self) -> ArrayD<f64> {
        ArrayD::from_shape_vec(IxDyn(&self.shape), self.data.clone())
            .expect("fixture shape and data length should agree")
    }
}

#[derive(Debug, Deserialize)]
struct UnaryFixture {
    input: Arr,
    output: Arr,
    grad: Arr,
}

/// Steps 34-35: `derivatives` is `[y, y', y'', ...]` for one input.
#[derive(Debug, Deserialize)]
struct HigherOrderFixture {
    input: Arr,
    derivatives: Vec<Arr>,
}

/// Step 33: the value, first and second derivative at one point.
#[derive(Debug, Deserialize)]
struct SecondDerivativeFixture {
    input: Arr,
    output: Arr,
    grad: Arr,
    grad2: Arr,
}

/// Step 33: every iterate of Newton's method, starting point included.
#[derive(Debug, Deserialize)]
struct NewtonFixture {
    start: f64,
    iterations: usize,
    trace: Vec<f64>,
}

#[derive(Debug, Deserialize)]
struct BinaryFixture {
    input0: Arr,
    input1: Arr,
    output: Arr,
    grad0: Arr,
    grad1: Arr,
}

/// Steps 37-40: a function of one variable and one target shape.
#[derive(Debug, Deserialize)]
struct ShapeFixture {
    input: Arr,
    shape: Vec<usize>,
    output: Arr,
    grad: Arr,
}

/// Steps 38-39: `sum` over `axis` (`null` for Python's `None`).
#[derive(Debug, Deserialize)]
struct SumFixture {
    input: Arr,
    axis: Option<isize>,
    keepdims: bool,
    output: Arr,
    grad: Arr,
}

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = format!(
        "{}/../../tests/parity/fixtures/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {path}: {e}"));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("fixture {name} should match the expected schema: {e}"))
}

fn assert_close(what: &str, actual: &ArrayD<f64>, expected: &ArrayD<f64>, rtol: f64) {
    assert_eq!(
        actual.shape(),
        expected.shape(),
        "{what}: shape mismatch (Rust {:?} vs Python {:?})",
        actual.shape(),
        expected.shape()
    );
    for (a, e) in actual.iter().zip(expected.iter()) {
        assert!(
            (a - e).abs() <= ATOL + rtol * e.abs(),
            "{what}: diverged from the Python reference\n  Rust:   {actual:?}\n  Python: {expected:?}"
        );
    }
}

fn data_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.data()
        .unwrap_or_else(|| panic!("{what} should hold data"))
}

fn grad_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.grad()
        .and_then(|g| g.data())
        .unwrap_or_else(|| panic!("{what} should have a gradient after backward"))
}

/// Build `x` from the fixture, apply `f`, run backward, compare both sides.
fn check_unary(name: &str, f: impl Fn(&Variable) -> Variable) {
    let fx: UnaryFixture = load(name);
    let x = Variable::new(fx.input.to_array());
    let y = f(&x);
    y.backward();

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close(
        &format!("{name} grad"),
        &grad_of(&x, name),
        &fx.grad.to_array(),
        GRAD_RTOL,
    );
}

/// Same, for two inputs -- checks the gradient of *both* operands.
fn check_binary(name: &str, f: impl Fn(&Variable, &Variable) -> Variable) {
    let fx: BinaryFixture = load(name);
    let a = Variable::new(fx.input0.to_array());
    let b = Variable::new(fx.input1.to_array());
    let y = f(&a, &b);
    y.backward();

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close(
        &format!("{name} grad0"),
        &grad_of(&a, name),
        &fx.grad0.to_array(),
        GRAD_RTOL,
    );
    assert_close(
        &format!("{name} grad1"),
        &grad_of(&b, name),
        &fx.grad1.to_array(),
        GRAD_RTOL,
    );
}

/// Replays the Python loop of steps 34-35: back-propagate with
/// `create_graph`, record `x.grad`, clear it, then back-propagate *that*.
///
/// The fixture's `derivatives` are `[y, y', y'', ...]`, so the loop runs one
/// backward pass more than it checks -- exactly like the generator, and the
/// extra pass is free coverage of the next order.
fn check_higher_order(name: &str, f: impl Fn(&Variable) -> Variable) {
    let fx: HigherOrderFixture = load(name);
    let (value, derivatives) = fx
        .derivatives
        .split_first()
        .unwrap_or_else(|| panic!("fixture {name} should record at least y itself"));

    let x = Variable::new(fx.input.to_array());
    let y = f(&x);
    y.backward_with(false, true);
    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &value.to_array(),
        RTOL,
    );

    for (order, expected) in derivatives.iter().enumerate() {
        let what = format!("{name} derivative {}", order + 1);
        let gx = x
            .grad()
            .unwrap_or_else(|| panic!("{what}: backward left no gradient on x"));
        assert_close(&what, &data_of(&gx, &what), &expected.to_array(), GRAD_RTOL);

        // `create_graph` again: the gradient we just checked has to remain
        // differentiable, or the next iteration has nothing to work on.
        x.cleargrad();
        gx.backward_with(false, true);
    }
}

/// How the Python generator seeded the gradients for a fixture.
#[derive(Debug, Clone, Copy)]
enum Seed {
    /// `y.backward()` -- ones over the output itself.
    Output,
    /// `F.sum(y).backward()` -- mathematically the same seed, but it also works
    /// when `y` *is* `x`, which is what `broadcast_to`/`sum_to` return when the
    /// shape already matches (no graph node, so `y.backward()` would have
    /// nothing to walk).
    ViaSum,
}

impl Seed {
    fn start(self, y: &Variable) {
        match self {
            Self::Output => y.backward(),
            Self::ViaSum => sum_all(y).backward(),
        }
    }
}

/// Build `x` from the fixture, apply `f` with the fixture's target shape,
/// back-propagate the way the generator did, compare both sides.
fn check_shaped(name: &str, seed: Seed, f: impl Fn(&Variable, &[usize]) -> Variable) {
    let fx: ShapeFixture = load(name);
    let x = Variable::new(fx.input.to_array());
    let y = f(&x, &fx.shape);
    seed.start(&y);

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close(
        &format!("{name} grad"),
        &grad_of(&x, name),
        &fx.grad.to_array(),
        GRAD_RTOL,
    );
}

/// Same, for `sum`'s `(axis, keepdims)` matrix.
fn check_sum(name: &str) {
    let fx: SumFixture = load(name);
    let x = Variable::new(fx.input.to_array());
    let axis = fx.axis.map_or(Axes::All, Axes::from);
    let y = sum(&x, axis, fx.keepdims);
    y.backward();

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close(
        &format!("{name} grad"),
        &grad_of(&x, name),
        &fx.grad.to_array(),
        GRAD_RTOL,
    );
}

/// The single scalar held by a 0-d variable.
fn scalar_of(v: &Variable, what: &str) -> f64 {
    let data = data_of(v, what);
    assert_eq!(data.len(), 1, "{what}: expected a single element");
    data.sum()
}

/// Step 33's objective, `y = x^4 - 2x^2`.
fn quartic(x: &Variable) -> Variable {
    pow(x, 4.0) - 2.0 * pow(x, 2.0)
}

// --- steps 02-08: single-variable functions and composition ---------------

/// The original step-02 fixture: forward only, and it pins `square()` itself
/// rather than the `x * x` spelling the other tests use.
#[test]
fn square_matches_python() {
    #[derive(Debug, Deserialize)]
    struct ForwardOnly {
        input: Arr,
        output: Arr,
    }

    let fx: ForwardOnly = load("square");
    let x = Variable::new(fx.input.to_array());
    let y = dezero::square(&x);

    assert_close(
        "square forward",
        &data_of(&y, "square"),
        &fx.output.to_array(),
        RTOL,
    );

    // The fixture only pins forward, but the same input exercises backward:
    // d(x^2)/dx = 2x.
    y.backward();
    let expected = fx.input.to_array().mapv(|v| 2.0 * v);
    assert_close("square grad", &grad_of(&x, "square"), &expected, GRAD_RTOL);
}

#[test]
fn exp_matches_python() {
    check_unary("exp", exp);
}

#[test]
fn square_backward_matches_python() {
    check_unary("square_backward", |x| x * x);
}

/// step 03's composed chain, `y = square(exp(square(x)))` -- the first case
/// that requires walking more than one link of the graph.
#[test]
fn composed_chain_matches_python() {
    check_unary("composed_sq_exp_sq", |x| {
        let t = exp(&(x * x));
        &t * &t
    });
}

// --- step 14: the same variable used twice must accumulate ---------------

/// `y = x + x` -> `dy/dx == 2`. Getting 1 here is the classic step-14 bug.
#[test]
fn repeated_variable_accumulates_grad() {
    check_unary("add_same_var", |x| x + x);
}

// --- steps 20-22: the arithmetic operator set ---------------------------

#[test]
fn add_matches_python() {
    check_binary("add", |a, b| a + b);
}

#[test]
fn mul_matches_python() {
    check_binary("mul", |a, b| a * b);
}

#[test]
fn sub_matches_python() {
    check_binary("sub", |a, b| a - b);
}

#[test]
fn div_matches_python() {
    check_binary("div", |a, b| a / b);
}

#[test]
fn neg_matches_python() {
    check_unary("neg", |x| -x);
}

#[test]
fn pow_matches_python() {
    check_unary("pow3", |x| dezero::pow(x, 3.0));
}

/// Mixes scalar operands, a reused variable, and four ops in one expression.
#[test]
fn composite_arithmetic_matches_python() {
    check_unary("composite_arith", |x| &((x * x) + x) / 2.0 - x);
}

// --- step 24: the book's benchmark optimisation functions ---------------
//
// Pure compositions of the ops above, but nested deeply enough to be a real
// exercise of the generation-ordered traversal. Each runs at 0-d (the book's
// own case) and at 2-d.

fn sphere(a: &Variable, b: &Variable) -> Variable {
    &(a * a) + &(b * b)
}

fn matyas(a: &Variable, b: &Variable) -> Variable {
    &(0.26 * (&(a * a) + &(b * b))) - &(0.48 * (a * b))
}

fn goldstein(a: &Variable, b: &Variable) -> Variable {
    let s = &(&(a + b) + 1.0);
    let left = 1.0
        + &(&(s * s)
            * &(&(&(&(19.0 - &(14.0 * a)) + &(3.0 * &(a * a))) - &(14.0 * b))
                + &(&(6.0 * &(a * b)) + &(3.0 * &(b * b)))));

    let t = &(&(2.0 * a) - &(3.0 * b));
    let right = 30.0
        + &(&(t * t)
            * &(&(&(&(18.0 - &(32.0 * a)) + &(12.0 * &(a * a))) + &(48.0 * b))
                + &(&(-36.0 * &(a * b)) + &(27.0 * &(b * b)))));

    &left * &right
}

#[test]
fn sphere_scalar_matches_python() {
    check_binary("sphere_scalar", sphere);
}

#[test]
fn sphere_2d_matches_python() {
    check_binary("sphere_2d", sphere);
}

#[test]
fn matyas_scalar_matches_python() {
    check_binary("matyas_scalar", matyas);
}

#[test]
fn matyas_2d_matches_python() {
    check_binary("matyas_2d", matyas);
}

#[test]
fn goldstein_scalar_matches_python() {
    check_binary("goldstein_scalar", goldstein);
}

#[test]
fn goldstein_2d_matches_python() {
    check_binary("goldstein_2d", goldstein);
}

// --- steps 27-35: trig/tanh and higher-order derivatives ------------------

#[test]
fn sin_matches_python() {
    check_unary("sin", sin);
}

#[test]
fn cos_matches_python() {
    check_unary("cos", cos);
}

#[test]
fn tanh_matches_python() {
    check_unary("tanh", tanh);
}

/// step 34: `sin` differentiated three times over `linspace(-7, 7, 21)`.
/// `sin -> cos -> -sin -> -cos` only comes out right if `Sin::backward`
/// builds its `cos(x)` through `apply`.
#[test]
fn sin_higher_order_matches_python() {
    check_higher_order("sin_higher_order", sin);
}

/// step 35: `tanh` to the second derivative at `x = 1`. Its backward reads
/// the *output* variable, so the second pass walks back through the very op
/// that produced it.
#[test]
fn tanh_higher_order_matches_python() {
    check_higher_order("tanh_higher_order", tanh);
}

/// step 33: `y = x^4 - 2x^2` at `x = 2` -> `y = 8`, `y' = 24`, `y'' = 44`.
#[test]
fn quartic_second_derivative_matches_python() {
    let fx: SecondDerivativeFixture = load("quartic_second_deriv");
    let x = Variable::new(fx.input.to_array());
    let y = quartic(&x);
    y.backward_with(false, true);

    assert_close(
        "quartic forward",
        &data_of(&y, "quartic"),
        &fx.output.to_array(),
        RTOL,
    );

    let gx = x.grad().expect("first derivative");
    assert_close(
        "quartic grad",
        &data_of(&gx, "quartic grad"),
        &fx.grad.to_array(),
        GRAD_RTOL,
    );

    x.cleargrad();
    gx.backward();
    assert_close(
        "quartic grad2",
        &grad_of(&x, "quartic grad2"),
        &fx.grad2.to_array(),
        GRAD_RTOL,
    );
}

/// step 33's headline: Newton's method driven entirely by automatic
/// differentiation, `x -= y' / y''`, compared iterate by iterate.
#[test]
fn newton_quartic_trace_matches_python() {
    let fx: NewtonFixture = load("newton_quartic");
    let x = Variable::from_scalar(fx.start);
    let mut trace = vec![fx.start];

    for _ in 0..fx.iterations {
        let y = quartic(&x);

        x.cleargrad();
        y.backward_with(false, true);
        let gx = x.grad().expect("first derivative");

        x.cleargrad();
        gx.backward();
        let gx2 = x.grad().expect("second derivative");

        let step = scalar_of(&gx, "y'") / scalar_of(&gx2, "y''");
        x.set_data(data_of(&x, "x") - step);
        trace.push(scalar_of(&x, "x"));
    }

    let shape = IxDyn(&[trace.len()]);
    let actual = ArrayD::from_shape_vec(shape.clone(), trace).expect("shape matches length");
    let expected = ArrayD::from_shape_vec(shape, fx.trace).expect("shape matches length");
    assert_close("newton trace", &actual, &expected, GRAD_RTOL);
}

// --- step 37: reshape / transpose -----------------------------------------

/// Every rank change that matters: flattening, adding an axis, folding two
/// axes together, and the degenerate `(1, 1) -> (1,)`.
#[test]
fn reshape_matches_python() {
    for name in [
        "reshape_2d_to_1d",
        "reshape_2d_to_3d",
        "reshape_3d_to_2d",
        "reshape_to_scalarish",
    ] {
        check_shaped(name, Seed::Output, reshape);
    }
}

#[test]
fn transpose_matches_python() {
    check_unary("transpose_2d", transpose);
}

// --- steps 38-39: sum over every axis/keepdims combination ----------------

#[test]
fn sum_matches_python() {
    for name in [
        "sum_all",
        "sum_all_keepdims",
        "sum_axis0",
        "sum_axis1",
        "sum_axis0_keepdims",
        "sum_axis1_keepdims",
        "sum_3d_axis0",
        "sum_3d_axis1",
        "sum_3d_axis2",
        "sum_3d_axis1_keepdims",
    ] {
        check_sum(name);
    }
}

// --- step 40: broadcast_to / sum_to ---------------------------------------
//
// The gradients in these fixtures were seeded from `F.sum(y)`, not `y`: when
// the requested shape already matches, Python returns `x` itself with no graph
// node, and `y.backward()` would have nothing to start from. Summing first is
// the same seed mathematically and covers the identity case too.

#[test]
fn broadcast_to_matches_python() {
    for name in [
        "broadcast_to_scalar_to_2d",
        "broadcast_to_row_to_2d",
        "broadcast_to_col_to_2d",
        "broadcast_to_1_to_3d",
        "broadcast_to_noop",
    ] {
        check_shaped(name, Seed::ViaSum, broadcast_to);
    }
}

#[test]
fn sum_to_matches_python() {
    for name in [
        "sum_to_2d_to_row",
        "sum_to_2d_to_col",
        "sum_to_2d_to_scalar",
        "sum_to_3d_to_2d",
        "sum_to_3d_to_1",
        "sum_to_noop",
    ] {
        check_shaped(name, Seed::ViaSum, sum_to);
    }
}

// --- step 40: broadcasting through the arithmetic ops ---------------------
//
// The forward values are the easy half. What these pin down is the *fold*:
// an operand that was stretched gets the sum over its copies back, and it must
// arrive at the operand's original shape rather than the broadcast one.

#[test]
fn broadcast_add_matches_python() {
    check_binary("bcast_add_row", |a, b| a + b);
    check_binary("bcast_add_col", |a, b| a + b);
    check_binary("bcast_add_scalar_arr", |a, b| a + b);
    check_binary("bcast_3d_add", |a, b| a + b);
}

#[test]
fn broadcast_mul_matches_python() {
    check_binary("bcast_mul_row", |a, b| a * b);
    check_binary("bcast_mul_col", |a, b| a * b);
}

#[test]
fn broadcast_sub_matches_python() {
    check_binary("bcast_sub_row", |a, b| a - b);
}

#[test]
fn broadcast_div_matches_python() {
    check_binary("bcast_div_row", |a, b| a / b);
}

/// The smaller operand on the *left*. `ndarray`'s own operators broadcast only
/// the right-hand side, so these two are the cases that would panic if the
/// forward pass leaned on them.
#[test]
fn broadcast_with_the_smaller_operand_first_matches_python() {
    check_binary("bcast_add_rev", |a, b| a + b);
    check_binary("bcast_sub_rev", |a, b| a - b);
}
