//! Parity tests for the convolution family (step 57) against golden fixtures
//! generated by the Python DeZero reference (`vendor/dezero-python`).
//!
//! These are rank-4 `[N, C, H, W]` tensors, so they exercise the fixture
//! format's rank-generality as much as the ops themselves.
//! Regenerate with `python tests/parity/gen_fixtures.py`.

use dezero::{Variable, conv2d, im2col, pooling, sum_all};
use ndarray::{ArrayD, IxDyn};
use serde::Deserialize;

/// numpy `allclose` defaults, for forward values.
const RTOL: f64 = 1e-5;
const ATOL: f64 = 1e-8;
/// Gradients travel through more arithmetic than the forward pass.
const GRAD_RTOL: f64 = 1e-4;

#[derive(Debug, Deserialize)]
struct Arr {
    shape: Vec<usize>,
    data: Vec<f64>,
}

impl Arr {
    fn to_array(&self) -> ArrayD<f64> {
        ArrayD::from_shape_vec(IxDyn(&self.shape), self.data.clone())
            .expect("fixture shape and data length should agree")
    }
}

#[derive(Debug, Deserialize)]
struct Im2colFixture {
    input: Arr,
    kernel: usize,
    stride: usize,
    pad: usize,
    output: Arr,
}

#[derive(Debug, Deserialize)]
struct Conv2dFixture {
    x: Arr,
    #[serde(rename = "W")]
    w: Arr,
    b: Arr,
    stride: usize,
    pad: usize,
    output: Arr,
    gx: Arr,
    #[serde(rename = "gW")]
    gw: Arr,
    gb: Arr,
}

#[derive(Debug, Deserialize)]
struct PoolingFixture {
    input: Arr,
    kernel: usize,
    stride: usize,
    pad: usize,
    output: Arr,
    grad: Arr,
}

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = format!(
        "{}/../../tests/parity/fixtures/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {path}: {e}"));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("fixture {name} should match the expected schema: {e}"))
}

fn assert_close(what: &str, actual: &ArrayD<f64>, expected: &ArrayD<f64>, rtol: f64) {
    assert_eq!(
        actual.shape(),
        expected.shape(),
        "{what}: shape mismatch (Rust {:?} vs Python {:?})",
        actual.shape(),
        expected.shape()
    );
    for (a, e) in actual.iter().zip(expected.iter()) {
        assert!(
            (a - e).abs() <= ATOL + rtol * e.abs(),
            "{what}: diverged from the Python reference\n  Rust:   {actual:?}\n  Python: {expected:?}"
        );
    }
}

fn data_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.data()
        .unwrap_or_else(|| panic!("{what} should hold data"))
}

fn grad_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.grad()
        .and_then(|g| g.data())
        .unwrap_or_else(|| panic!("{what} should have a gradient after backward"))
}

// --- im2col --------------------------------------------------------------

fn check_im2col(name: &str) {
    let fx: Im2colFixture = load(name);
    let x = Variable::new(fx.input.to_array());
    let y = im2col(&x, fx.kernel, fx.stride, fx.pad, true);
    assert_close(name, &data_of(&y, name), &fx.output.to_array(), RTOL);
}

#[test]
fn im2col_k3s1p0_matches_python() {
    check_im2col("im2col_k3s1p0");
}

#[test]
fn im2col_k3s2p1_matches_python() {
    check_im2col("im2col_k3s2p1");
}

// --- conv2d --------------------------------------------------------------

/// Forward *and* all three gradients. The fixture seeds backward from
/// `F.sum(y)`, so this does the same.
fn check_conv2d(name: &str) {
    let fx: Conv2dFixture = load(name);
    let x = Variable::new(fx.x.to_array());
    let w = Variable::new(fx.w.to_array());
    let b = Variable::new(fx.b.to_array());

    let y = conv2d(&x, &w, Some(&b), fx.stride, fx.pad);
    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );

    sum_all(&y).backward();
    assert_close(
        &format!("{name} gx"),
        &grad_of(&x, name),
        &fx.gx.to_array(),
        GRAD_RTOL,
    );
    assert_close(
        &format!("{name} gW"),
        &grad_of(&w, name),
        &fx.gw.to_array(),
        GRAD_RTOL,
    );
    assert_close(
        &format!("{name} gb"),
        &grad_of(&b, name),
        &fx.gb.to_array(),
        GRAD_RTOL,
    );
}

#[test]
fn conv2d_s1p0_matches_python() {
    check_conv2d("conv2d_s1p0");
}

/// Padding: the output keeps the input's spatial size, `[2,4,5,5]`.
#[test]
fn conv2d_s1p1_matches_python() {
    check_conv2d("conv2d_s1p1");
}

/// Stride *and* padding together -- the combination that gets the output-size
/// arithmetic wrong if `get_conv_outsize` is off by one.
#[test]
fn conv2d_s2p1_matches_python() {
    check_conv2d("conv2d_s2p1");
}

// --- max pooling ---------------------------------------------------------

fn check_pooling(name: &str) {
    let fx: PoolingFixture = load(name);
    let x = Variable::new(fx.input.to_array());

    let y = pooling(&x, fx.kernel, fx.stride, fx.pad);
    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );

    sum_all(&y).backward();
    assert_close(
        &format!("{name} grad"),
        &grad_of(&x, name),
        &fx.grad.to_array(),
        GRAD_RTOL,
    );
}

/// Non-overlapping windows: every input element belongs to exactly one window.
#[test]
fn pooling_k2s2p0_matches_python() {
    check_pooling("pooling_k2s2p0");
}

/// Overlapping windows with padding -- here an input element can win several
/// windows, so its gradient accumulates. That is where a scatter that
/// overwrites instead of adding would show up.
#[test]
fn pooling_k3s1p1_matches_python() {
    check_pooling("pooling_k3s1p1");
}
