//! Parity tests for the neural-network layer — steps 41–48 — against golden
//! fixtures generated by the Python DeZero reference (`vendor/dezero-python`).
//!
//! Split out from `parity_core.rs`, which covers the autodiff engine itself.
//! The two files share a handful of small fixture helpers by copy rather than
//! through a `tests/common` module, so that each stands on its own and neither
//! can be broken by an edit meant for the other; nothing here is worth the
//! coupling.
//!
//! The last test is the one that matters most. `training_two_layer` replays a
//! complete 50-iteration training run — `Linear`, `sigmoid`, `Linear`,
//! `mean_squared_error`, `SGD` — against Python's loss at every single step and
//! its four weight arrays at the end. Every piece of steps 41–46 has to be
//! right simultaneously for it to pass.
//!
//! Regenerate with `python tests/parity/gen_fixtures.py`.

use dezero::{
    Layer, Linear, Optimizer, Parameter, Sgd, Variable, linear, matmul, mean_squared_error, relu,
    sigmoid, sum_all,
};
use ndarray::{ArrayD, IxDyn};
use serde::Deserialize;

/// numpy `allclose` defaults, for forward values.
const RTOL: f64 = 1e-5;
const ATOL: f64 = 1e-8;
/// Gradients accumulate through more floating-point operations than the
/// forward pass, so they get a looser bound -- still far tighter than any
/// real bug would survive.
const GRAD_RTOL: f64 = 1e-4;

/// An ndarray serialised rank-generically: `shape: []` is a 0-d scalar.
#[derive(Debug, Deserialize)]
struct Arr {
    shape: Vec<usize>,
    data: Vec<f64>,
}

impl Arr {
    fn to_array(&self) -> ArrayD<f64> {
        ArrayD::from_shape_vec(IxDyn(&self.shape), self.data.clone())
            .expect("fixture shape and data length should agree")
    }

    fn to_variable(&self) -> Variable {
        Variable::new(self.to_array())
    }
}

#[derive(Debug, Deserialize)]
struct UnaryFixture {
    input: Arr,
    output: Arr,
    grad: Arr,
}

#[derive(Debug, Deserialize)]
struct BinaryFixture {
    input0: Arr,
    input1: Arr,
    output: Arr,
    grad0: Arr,
    grad1: Arr,
}

/// Steps 42-43: `linear(x, W, b)`, with all three gradients seeded from
/// `F.sum(y)`.
#[derive(Debug, Deserialize)]
struct LinearFixture {
    x: Arr,
    #[serde(rename = "W")]
    w: Arr,
    b: Arr,
    output: Arr,
    gx: Arr,
    #[serde(rename = "gW")]
    gw: Arr,
    gb: Arr,
}

/// Step 47: integer class labels are not differentiable, so this one is not a
/// binary fixture -- there is a gradient for the logits and nothing else.
#[derive(Debug, Deserialize)]
struct CrossEntropyFixture {
    logits: Arr,
    labels: Vec<usize>,
    output: Arr,
    grad: Arr,
}

/// Steps 42-46: a complete training run with every initial weight pinned.
#[derive(Debug, Deserialize)]
struct TrainingFixture {
    x: Arr,
    y: Arr,
    #[serde(rename = "W1")]
    w1: Arr,
    b1: Arr,
    #[serde(rename = "W2")]
    w2: Arr,
    b2: Arr,
    lr: f64,
    iterations: usize,
    losses: Vec<f64>,
    #[serde(rename = "final_W1")]
    final_w1: Arr,
    final_b1: Arr,
    #[serde(rename = "final_W2")]
    final_w2: Arr,
    final_b2: Arr,
}

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = format!(
        "{}/../../tests/parity/fixtures/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {path}: {e}"));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("fixture {name} should match the expected schema: {e}"))
}

fn assert_close(what: &str, actual: &ArrayD<f64>, expected: &ArrayD<f64>, rtol: f64) {
    assert_eq!(
        actual.shape(),
        expected.shape(),
        "{what}: shape mismatch (Rust {:?} vs Python {:?})",
        actual.shape(),
        expected.shape()
    );
    for (a, e) in actual.iter().zip(expected.iter()) {
        assert!(
            (a - e).abs() <= ATOL + rtol * e.abs(),
            "{what}: diverged from the Python reference\n  Rust:   {actual:?}\n  Python: {expected:?}"
        );
    }
}

fn data_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.data()
        .unwrap_or_else(|| panic!("{what} should hold data"))
}

fn grad_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.grad()
        .and_then(|g| g.data())
        .unwrap_or_else(|| panic!("{what} should have a gradient after backward"))
}

/// Build `x` from the fixture, apply `f`, run backward, compare both sides.
fn check_unary(name: &str, f: impl Fn(&Variable) -> Variable) {
    let fx: UnaryFixture = load(name);
    let x = fx.input.to_variable();
    let y = f(&x);
    y.backward();

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close(
        &format!("{name} grad"),
        &grad_of(&x, name),
        &fx.grad.to_array(),
        GRAD_RTOL,
    );
}

/// Same, for two inputs -- checks the gradient of *both* operands.
fn check_binary(name: &str, f: impl Fn(&Variable, &Variable) -> Variable) {
    let fx: BinaryFixture = load(name);
    let a = fx.input0.to_variable();
    let b = fx.input1.to_variable();
    let y = f(&a, &b);
    y.backward();

    assert_close(
        &format!("{name} forward"),
        &data_of(&y, name),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close(
        &format!("{name} grad0"),
        &grad_of(&a, name),
        &fx.grad0.to_array(),
        GRAD_RTOL,
    );
    assert_close(
        &format!("{name} grad1"),
        &grad_of(&b, name),
        &fx.grad1.to_array(),
        GRAD_RTOL,
    );
}

// --- step 41: matmul ------------------------------------------------------

/// A rectangular product and the degenerate row-by-column one. The gradients
/// are the real content: `gx = gy . W^T` and `gW = x^T . gy` are easy to write
/// with the transposes on the wrong side, and both wrong versions still have
/// the right shape when the matrices are square.
#[test]
fn matmul_matches_python() {
    check_binary("matmul_2x3_3x4", matmul);
    check_binary("matmul_1x3_3x1", matmul);
}

// --- steps 42-43: linear --------------------------------------------------

/// The fused affine transform, with all three gradients checked at once.
/// `gb` is the one that distinguishes `linear` from `matmul` + `+`: the bias
/// was broadcast down the batch, so its gradient is the column sums of `gy`.
#[test]
fn linear_matches_python() {
    let fx: LinearFixture = load("linear");
    let x = fx.x.to_variable();
    let w = fx.w.to_variable();
    let b = fx.b.to_variable();

    let y = linear(&x, &w, Some(&b));
    // The generator seeded from `F.sum(y)`, not from `y`.
    sum_all(&y).backward();

    assert_close(
        "linear forward",
        &data_of(&y, "linear"),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close("linear gx", &grad_of(&x, "x"), &fx.gx.to_array(), GRAD_RTOL);
    assert_close("linear gW", &grad_of(&w, "W"), &fx.gw.to_array(), GRAD_RTOL);
    assert_close("linear gb", &grad_of(&b, "b"), &fx.gb.to_array(), GRAD_RTOL);
}

/// Without a bias, `linear` must be `matmul` exactly -- the same fixture, with
/// the bias contribution removed by hand.
#[test]
fn linear_without_a_bias_matches_matmul() {
    let fx: LinearFixture = load("linear");
    let x = fx.x.to_variable();
    let w = fx.w.to_variable();

    let expected = fx.output.to_array() - fx.b.to_array();
    assert_close(
        "linear (no bias) forward",
        &data_of(&linear(&x, &w, None), "linear"),
        &expected,
        RTOL,
    );
}

// --- step 43: activations -------------------------------------------------

#[test]
fn sigmoid_matches_python() {
    check_unary("sigmoid", sigmoid);
}

#[test]
fn relu_matches_python() {
    check_unary("relu", relu);
}

/// The softmax fixture's gradient is all zeros, and correctly so: with a seed
/// of ones, `y * gy - y * sum(y * gy)` is `y - y * 1`. It still pins the
/// forward pass, and the *shape* of the backward pass; the non-trivial
/// gradient is covered by the library's own `gradient_check` and by the
/// cross-entropy fixture below.
#[test]
fn softmax_matches_python() {
    check_unary("softmax", dezero::softmax);
}

// --- step 47: softmax cross entropy ---------------------------------------

/// The gather in the forward pass and the scatter in the backward pass, both
/// hand-written because `ndarray` has no fancy indexing. A gather that read the
/// wrong element still produces a plausible loss; only the reference value
/// catches it.
#[test]
fn softmax_cross_entropy_matches_python() {
    let fx: CrossEntropyFixture = load("softmax_cross_entropy");
    let logits = fx.logits.to_variable();

    let loss = dezero::softmax_cross_entropy(&logits, &fx.labels);
    loss.backward();

    assert_close(
        "softmax_cross_entropy forward",
        &data_of(&loss, "loss"),
        &fx.output.to_array(),
        RTOL,
    );
    assert_close(
        "softmax_cross_entropy grad",
        &grad_of(&logits, "logits"),
        &fx.grad.to_array(),
        GRAD_RTOL,
    );
}

// --- step 42: mean squared error ------------------------------------------

#[test]
fn mean_squared_error_matches_python() {
    check_binary("mean_squared_error", mean_squared_error);
}

// --- steps 42-46: the whole training loop ---------------------------------

/// The Python generator's network: `Linear(1 -> 10)`, `sigmoid`,
/// `Linear(10 -> 1)`.
///
/// Written out rather than assembled from [`dezero::Mlp`] so that the
/// registration this step is really about -- `own_params` and `sublayers`,
/// standing in for Python's `__setattr__` hook -- is exercised as a user would
/// write it.
struct TwoLayer {
    first: Linear,
    second: Linear,
}

impl Layer for TwoLayer {
    fn own_params(&self) -> Vec<Parameter> {
        Vec::new()
    }

    fn sublayers(&self) -> Vec<&dyn Layer> {
        vec![&self.first, &self.second]
    }

    fn forward(&self, x: &Variable) -> Variable {
        self.second.forward(&sigmoid(&self.first.forward(x)))
    }
}

/// Replays the reference's 50-iteration training run step for step.
///
/// This is the integration test for steps 41-46 taken together: `Parameter`,
/// `Layer` registration, `Linear`, `sigmoid`, `mean_squared_error`, the
/// backward pass, `cleargrads` and `SGD`. Any one of them wrong and the loss
/// trace diverges -- usually within a handful of iterations, because each
/// iteration's weights are the previous one's output.
///
/// Every initial weight comes from the fixture. Rust's generator will never
/// reproduce numpy's stream (`docs/ARCHITECTURE.md`), so "seed both sides" is
/// not an option and never was.
#[test]
fn two_layer_training_run_matches_python() {
    let fx: TrainingFixture = load("training_two_layer");

    let x = fx.x.to_variable();
    let y = fx.y.to_variable();

    let model = TwoLayer {
        first: Linear::with_in_size(1, 10),
        second: Linear::with_in_size(10, 1),
    };
    model.first.weight().set_data(fx.w1.to_array());
    model
        .first
        .bias()
        .expect("Linear has a bias by default")
        .set_data(fx.b1.to_array());
    model.second.weight().set_data(fx.w2.to_array());
    model
        .second
        .bias()
        .expect("Linear has a bias by default")
        .set_data(fx.b2.to_array());

    let mut optimizer = Sgd::new(fx.lr);
    optimizer.setup(&model);

    assert_eq!(
        fx.losses.len(),
        fx.iterations,
        "the fixture should record one loss per iteration"
    );

    let mut losses = Vec::with_capacity(fx.iterations);
    for _ in 0..fx.iterations {
        let prediction = model.forward(&x);
        let loss = mean_squared_error(&prediction, &y);
        model.cleargrads();
        loss.backward();
        optimizer.update();
        losses.push(data_of(&loss, "loss").sum());
    }

    // Compared iteration by iteration rather than only at the end: a divergence
    // shows up at the step it started on, not fifty steps later.
    let shape = IxDyn(&[losses.len()]);
    let actual = ArrayD::from_shape_vec(shape.clone(), losses).expect("shape matches length");
    let expected = ArrayD::from_shape_vec(shape, fx.losses).expect("shape matches length");
    assert_close("training loss trace", &actual, &expected, GRAD_RTOL);

    // The trace could in principle match while the weights drifted, so the
    // final parameters are pinned too.
    for (what, actual, expected) in [
        ("W1", model.first.weight(), &fx.final_w1),
        ("b1", model.first.bias().expect("bias"), &fx.final_b1),
        ("W2", model.second.weight(), &fx.final_w2),
        ("b2", model.second.bias().expect("bias"), &fx.final_b2),
    ] {
        assert_close(
            &format!("final {what}"),
            &data_of(actual, what),
            &expected.to_array(),
            GRAD_RTOL,
        );
    }
}

/// The same run, but the network's weights are lazily shaped: the layers are
/// built with no `in_size` at all and sized by the first batch. The trace must
/// be identical, which is the proof that the lazy path differs from the eager
/// one only in *when* the weight array is allocated.
#[test]
fn the_lazy_weight_path_reproduces_the_same_training_run() {
    let fx: TrainingFixture = load("training_two_layer");
    let x = fx.x.to_variable();
    let y = fx.y.to_variable();

    let model = TwoLayer {
        first: Linear::new(10),
        second: Linear::new(1),
    };

    // Registered *before* the weights exist -- the case the whole
    // `Parameter::empty` design is for.
    let mut optimizer = Sgd::new(fx.lr);
    optimizer.setup(&model);
    assert_eq!(optimizer.params().len(), 4);
    assert!(model.first.weight().data().is_none());

    // One forward pass fixes the shapes; then overwrite with Python's weights.
    model.forward(&x);
    assert_eq!(model.first.in_size(), Some(1));
    assert_eq!(model.second.in_size(), Some(10));

    model.first.weight().set_data(fx.w1.to_array());
    model.first.bias().expect("bias").set_data(fx.b1.to_array());
    model.second.weight().set_data(fx.w2.to_array());
    model
        .second
        .bias()
        .expect("bias")
        .set_data(fx.b2.to_array());
    model.cleargrads();

    for expected in &fx.losses {
        let loss = mean_squared_error(&model.forward(&x), &y);
        model.cleargrads();
        loss.backward();
        optimizer.update();

        let actual = data_of(&loss, "loss").sum();
        assert!(
            (actual - expected).abs() <= ATOL + GRAD_RTOL * expected.abs(),
            "lazy path diverged: got {actual}, Python had {expected}"
        );
    }

    assert_close(
        "final W1 (lazy path)",
        &data_of(model.first.weight(), "W1"),
        &fx.final_w1.to_array(),
        GRAD_RTOL,
    );
}
