//! Parity tests for the recurrent layers (steps 59–60) against golden fixtures
//! generated by the Python DeZero reference (`vendor/dezero-python`).
//!
//! Both fixtures unroll three timesteps with the weights pinned, so they check
//! the *state carried between calls* — the thing that makes these layers
//! different from every layer before them — and not just one forward pass.
//! Regenerate with `python tests/parity/gen_fixtures.py`.

use dezero::{Layer, Lstm, Rnn, Variable, sum_all};
use ndarray::{ArrayD, IxDyn};
use serde::Deserialize;

const RTOL: f64 = 1e-5;
const ATOL: f64 = 1e-8;

#[derive(Debug, Deserialize)]
struct Arr {
    shape: Vec<usize>,
    data: Vec<f64>,
}

impl Arr {
    fn to_array(&self) -> ArrayD<f64> {
        ArrayD::from_shape_vec(IxDyn(&self.shape), self.data.clone())
            .expect("fixture shape and data length should agree")
    }
}

#[derive(Debug, Deserialize)]
struct RnnFixture {
    #[serde(rename = "x2h_W")]
    x2h_w: Arr,
    x2h_b: Arr,
    #[serde(rename = "h2h_W")]
    h2h_w: Arr,
    inputs: Vec<Arr>,
    states: Vec<Arr>,
}

#[derive(Debug, Deserialize)]
struct LstmFixture {
    #[serde(rename = "x2f_W")]
    x2f_w: Arr,
    x2f_b: Arr,
    #[serde(rename = "x2i_W")]
    x2i_w: Arr,
    x2i_b: Arr,
    #[serde(rename = "x2o_W")]
    x2o_w: Arr,
    x2o_b: Arr,
    #[serde(rename = "x2u_W")]
    x2u_w: Arr,
    x2u_b: Arr,
    #[serde(rename = "h2f_W")]
    h2f_w: Arr,
    #[serde(rename = "h2i_W")]
    h2i_w: Arr,
    #[serde(rename = "h2o_W")]
    h2o_w: Arr,
    #[serde(rename = "h2u_W")]
    h2u_w: Arr,
    inputs: Vec<Arr>,
    states: Vec<Arr>,
}

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = format!(
        "{}/../../tests/parity/fixtures/{name}.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {path}: {e}"));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("fixture {name} should match the expected schema: {e}"))
}

fn assert_close(what: &str, actual: &ArrayD<f64>, expected: &ArrayD<f64>) {
    assert_eq!(
        actual.shape(),
        expected.shape(),
        "{what}: shape mismatch (Rust {:?} vs Python {:?})",
        actual.shape(),
        expected.shape()
    );
    for (a, e) in actual.iter().zip(expected.iter()) {
        assert!(
            (a - e).abs() <= ATOL + RTOL * e.abs(),
            "{what}: diverged from the Python reference\n  Rust:   {actual:?}\n  Python: {expected:?}"
        );
    }
}

fn data_of(v: &Variable, what: &str) -> ArrayD<f64> {
    v.data()
        .unwrap_or_else(|| panic!("{what} should hold data"))
}

// --- step 59: RNN --------------------------------------------------------

/// Three timesteps of an Elman RNN. Step 1 uses only `x2h`; steps 2 and 3 add
/// the recurrent term, so a state that failed to carry would match on the
/// first row and diverge after.
#[test]
fn rnn_unrolled_matches_python() {
    let fx: RnnFixture = load("rnn_unrolled");
    let hidden = fx.x2h_w.shape[1];
    let in_size = fx.x2h_w.shape[0];

    let rnn = Rnn::with_in_size(in_size, hidden);
    rnn.x2h().weight().set_data(fx.x2h_w.to_array());
    rnn.x2h()
        .bias()
        .expect("x2h carries a bias")
        .set_data(fx.x2h_b.to_array());
    rnn.h2h().weight().set_data(fx.h2h_w.to_array());

    assert_eq!(fx.inputs.len(), fx.states.len());
    for (step, (x, expected)) in fx.inputs.iter().zip(&fx.states).enumerate() {
        let h = rnn.forward(&Variable::new(x.to_array()));
        assert_close(
            &format!("rnn state after step {}", step + 1),
            &data_of(&h, "rnn state"),
            &expected.to_array(),
        );
    }
}

/// Back-propagating from the last state must reach every weight, through all
/// three steps — that is BPTT.
#[test]
fn rnn_bptt_reaches_every_weight() {
    let fx: RnnFixture = load("rnn_unrolled");
    let rnn = Rnn::with_in_size(fx.x2h_w.shape[0], fx.x2h_w.shape[1]);
    rnn.x2h().weight().set_data(fx.x2h_w.to_array());
    rnn.x2h()
        .bias()
        .expect("x2h carries a bias")
        .set_data(fx.x2h_b.to_array());
    rnn.h2h().weight().set_data(fx.h2h_w.to_array());

    let mut last = None;
    for x in &fx.inputs {
        last = Some(rnn.forward(&Variable::new(x.to_array())));
    }
    sum_all(&last.expect("three steps ran")).backward();

    for p in rnn.params() {
        assert!(p.grad().is_some(), "BPTT reaches every parameter");
    }
}

// --- step 60: LSTM -------------------------------------------------------

/// Three timesteps of an LSTM. Both `h` and `c` carry, and `c` is invisible in
/// the output except through its effect on later steps — so this is the test
/// that catches a cell state that fails to persist.
#[test]
fn lstm_unrolled_matches_python() {
    let fx: LstmFixture = load("lstm_unrolled");
    let in_size = fx.x2f_w.shape[0];
    let hidden = fx.x2f_w.shape[1];

    let lstm = Lstm::with_in_size(in_size, hidden);

    // Python's field order is forget, input, output, candidate.
    let input_w = [&fx.x2f_w, &fx.x2i_w, &fx.x2o_w, &fx.x2u_w];
    let input_b = [&fx.x2f_b, &fx.x2i_b, &fx.x2o_b, &fx.x2u_b];
    for ((gate, w), b) in lstm.input_gates().iter().zip(input_w).zip(input_b) {
        gate.weight().set_data(w.to_array());
        gate.bias()
            .expect("input-side gates carry a bias")
            .set_data(b.to_array());
    }

    let recurrent_w = [&fx.h2f_w, &fx.h2i_w, &fx.h2o_w, &fx.h2u_w];
    for (gate, w) in lstm.recurrent_gates().iter().zip(recurrent_w) {
        gate.weight().set_data(w.to_array());
        assert!(gate.bias().is_none(), "recurrent gates have no bias");
    }

    assert_eq!(fx.inputs.len(), fx.states.len());
    for (step, (x, expected)) in fx.inputs.iter().zip(&fx.states).enumerate() {
        let h = lstm.forward(&Variable::new(x.to_array()));
        assert_close(
            &format!("lstm state after step {}", step + 1),
            &data_of(&h, "lstm state"),
            &expected.to_array(),
        );
    }

    assert!(
        lstm.cell_state().is_some(),
        "the cell state is carried alongside the hidden state"
    );
}
